-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 15b678e9c67c42765c3d579e40672a332f4366d7
    hooks:
    -   id: autopep8-wrapper
        args: ['-i', '-a', '-a', '--max-line-length=160']
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: trailing-whitespace

-   repo: git://github.com/pricematch/pricematch-pre-commit-hooks
    sha: dd2447ada6d23bb9338d074f9453261924a26a77
    hooks:
    -   id: do_not_commit
